return {
	["Menu"] = true,
	["Music"] = 1,
	["Debug"] = false,
	["Partymusic"] = true,
	["Santamusic"] = true,
	["Hyperascendantmusic"] = true,
	["Yottamusic"] = true,
	["Editionmusic"] = true,
	["Ultrablindmusic"] = true,
	["TameSounds"] = false,
	["CustomHyperoperations"] = true,
	["Mode"] = 1,
	["Limit"] = 2,
	["Scaling"] = 1,
	["Params"] = 1,
	["TrEffects"] = 4,
	["TrAudio"] = 100,
	["TrShakeCards"] = true,
	["TrShakeScreen"] = true,
	["WindowShake"] = true,
	["JokerEffects"] = true,
	["Safe"] = false,
	["content"] = {
		["WIP"] = true,
		["Jokers"] = true,
		["FusionJokers"] = true,
		["Consumables"] = true,
		["Vouchers"] = true,
		["UltraBlinds"] = true,
		["Blinds"] = true,
		["Enhancements"] = true,
		["Editions"] = true,
		["Boosters"] = true,
	},
	["CM"] = {
		["Cryptid"] = true,
		["BlindEditions"] = true,
		["Grim"] = true,
	},
	["Shakiness"] = {
		["quiverlimit"] = 25,
		["pulselimit"] = 25,
		["unlimitquiver"] = true,
		["unlimitpulse"] = true,
		["shake_screen"] = true,
	},
	["transcendence_counter"] = false,
	["massuse"] = true,
}