[manifest]
version = "1.0.0"
dump_lua = true
priority = 1000000000

# Progress bar color 
[[patches]] 
[patches.pattern]
target = '''main.lua'''
pattern = '''love.graphics.setColor(0.6, 0.8, 0.9, 1)'''
position = "at"
payload = '''love.graphics.setColor(0.9, 0, 0, 1)'''
match_indent = true
overwrite = true

# Init fun facts
[[patches]] 
[patches.pattern]
target = '''main.lua'''
pattern = '''local catimg = NFS.getInfo(SMODS.path.."assets/cat.png") and love.graphics.newImage(love.filesystem.newFileData(NFS.read(SMODS.path.."assets/cat.png")))'''
position = "before"
payload = '''
	MAY_fun_facts = {
		"Mr. Nacho exists in real life, and is a bag of cheap tortilla chips from a German discount hypermarket.", 
		"AAAA was the first Joker added to Mayhem, and used to be Uncommon.", 
		"Mayhem was supposed to be vanilla+, and was called Stupidum.", 
		"Universal Collapse has had 7 sprites in its history, 3 of which were never actually added.",
		"If you like Mayhem's music, you should check out Balatro XD Mods OST on the repository.",
		"Update 0.0.2 alone took 2 months to develop, and practically doubled the mod.",
		"1.0.0 is actually 0.0.3, however I changed the versioning system. It also took 4 months to develop.",
		"Diskus is one of the biggest reasons Mayhem requires Noituus.",
		"Mayhem started in October 2024, it's just that I posted it in the Balatro server in July 2025.", 
		"Shout-out to all Mayhem content creators: Exattox, TheUnseenExplosion, Machine Gamer 728, XZ0204, bdoy, pawPatoes, Kristian_0000, drplushie231",
		'Shout-out to all of my "Nacho" beta testers! There\'s too many to list them all here...', 
		"Shout-out to all of the people who've contributed art to this mod! Hover over an item to see who sprited it.",
		"I HATE CRYPTID I HATE CRYPTID I HATE CRYPTID I HATE CRYPTID I HATE CRYPTID I HATE CRYPTID",
		"Tetration (^^) is repeated exponentiation, pentation (^^^) is repeated tetration. {2} = tetration, {3} = pentation, {4} = hexation...",
		"ee5 = 1e(1e5) (1 with 100,000 zeroes); eee5 = e5#3; e5#3#2 = e5#(e5#3); e5#3#4 = e5#(e5#(e5#(e5#(e5#3)))); e5##2 = e5#5; e5##4 = e5#5#5#5#5",
		"If a run ever gets too laggy, you can try restarting the game. Some of the lag will usually go away.",
		"Pretty much every single piece of content in Mayhem has been changed since launch.",
		"THE DAWN OF A NEW ERA",
		"Also try other mods! These are passion projects, go support them, you are what keeps us going!", 
		"Ah yes, the store! The classic place we all go to buy things we need! When I go to the store, I like to buy cheese! What do you like to buy from the store?",
		"h.",
		"I just want to thank you for playing. Mayhem is my first ever proper online project and I am eternally grateful for it's success.",
		"Mayhem is compatible-ish with Hot Potato and Multiplayer. Give them a try if you want some chaos!", 
		"Unexpected error: attempt to compare number with table", 
		"There's a fun fact here that has a 1 in 1000 chance of appearing. Keep your eyes peeled!", 
		"Fun facts are stored in Mayhem/lovely/loading_screen.toml. Look there if you're boring and want to see all of them at once.", 
		"Mayhem is bigger than Balatro in terms of disk space.",
		"Most of Mayhem's Planet Cards are actual astronomical objects. Those without position indicators at the top are fictional.",
		"Transcendence effects were a last-minute addition to Mayhem, 1 or 2 months before launch.",
		"Including this one, update 1.3.0-pre4 added 4 new fun facts here.",
		"I make Friday Night Funkin' spamtracks. Just in case you didn't think I'm insane already.",
		"There are plenty of references in Mayhem, however most of them are very obscure.",
		"Do not look in joker2.png.",
		"Omniversal Catalyst used to be called Universal Collapse. Many Joker names were changed in 1.4.0.",
		"I'm Romanian!", 
		"Red is my favorite color. That's why Mayhem is red.",
		"As Ultimatum was the first Transcendent Joker in Mayhem.",
		"Diskus Distruktum was created before Diskus Kollectum and Diskus Dominus.",
		"You are loved.", 
		"MEHM SUPREMACY", 
		"If you're seeing this, you are not blind!", 
		"Mayhem used to have a 2nd, much more broken gameset called Eternum. It was removed since it sucked.",
		"The 2nd Transcendence ambiance has been unchanged since launch, minus a few small changes.",
		"Endless Mode used to activate instantly when selecting a Blind after Ante 9; the Voucher didn't exist.",
		"Mayhem had BOOK OF SHADOWS cross-mod in the pre-release days.",
		"I found Alptraum in the Geometry Dash audio library.", 
		"There was a Tag in in the 0.0.2 versions that literally gave you a Perishable lategame Joker for free.", 
		"Genesis used to multiply your Ante. That was removed since it made the mod practically impossible.", 
		"Anniversary Cake is heavily based on the Birthday levels from the original Angry Birds.", 
		"Mayhem had an entire set of N Jokers based on Three of a Kind and Sly Joker. They were removed as they were very bloaty.",
		"Mayhem had an exploit which allowed you to generate *trillions* of Consumables with the SAVESCUM Retro Card.",
	} 
	
	table.insert(MAY_fun_facts, "Including this one, there are currently "..(#MAY_fun_facts + 2).." possible fun facts here.")
	if math.random(1000) == 1000 then 
		MAY_fun_fact = "This fun fact has a 1 in 1000 chance of appearing."
	else
		MAY_fun_fact = MAY_fun_facts[math.random(#MAY_fun_facts)]
	end
'''
match_indent = true
overwrite = true

# Display fun fact
[[patches]] 
[patches.pattern]
target = '''main.lua'''
pattern = '''love.graphics.print("LOADING: " .. _next, realw / 2 - 150, realh / 2 + 40)'''
position = "after"
payload = '''

	local function centered_text(rectX, rectY, rectWidth, rectHeight, text, size)
		local font = love.graphics.getFont()
		local textWidth = font:getWidth(text)
		local textHeight = font:getHeight()
		love.graphics.print(text, rectX+rectWidth/2, rectY+rectHeight/2, 0, size, size, textWidth/2, textHeight/2)
	end 
	
	centered_text(0, -65, realw, realh, "MAYHEM", 1)
	centered_text(0, 120, realw, realh, (MAY_fun_fact or "ERROR (something actually broke, please report this)") , 1)
'''
match_indent = true
overwrite = true

# Error message if dependencies are missing because people are incapable of reading 
[[patches]] 
[patches.pattern]
target = "game.lua"
pattern = "function Game:splash_screen()"
position = "after"
payload = '''
if (not Noituus) and (not Overflow) then
    error("MAYHEM: Missing dependency: Noituus | Make sure it is installed properly.") 
end
if not Talisman then
	error("MAYHEM: Missing dependency: Amulet | Make sure it is installed properly and is on a supported version.")
end
if #SMODS.find_mod('Spectrallib') == 0 then
	error("MAYHEM: Missing dependency: SpectralLib | Make sure it is installed properly and is on a supported version.")
end
if not may then 
	error([[
		MAYHEM: Unidentified installation error. Please make sure that Mayhem and its dependencies are installed correctly.
		Here are some other possible causes:
		- Unsupported Steamodded version. Make sure Steamodded is on a stable and supported version. It is recommended you use the version packaged in the Dependencies ZIP on Mayhem's release page.
		- Nested folders. Your Mods folder should contain folders which then contain the files for each mod. Do not install mods in the following way: Mods/Mayhem 1.4.0/Mayhem/...; this is wrong and will result in a crash. 
		- Unsupported Lovely version. Make sure Lovely Injector is up to date. 
		- Leftover ZIP files. Steamodded can load mods from ZIP files, so make sure you haven't left any ZIP files in your mods folder. 
		- A mod may have interfered with Mayhem on launch or is a stated conflict. Please remove any mods you might consider problematic. 
		- Firmware issue. Mayhem is only tested on Windows and Android and is confirmed to work on MacOS. Problems may reveal themselves on Linux, albeit this is unlikely. 
		If this crash persists, you are free to contact me with details on how you installed the mod.
	]]) 
end
'''
match_indent = true
overwrite = true