[manifest]
version = "1.0.0"
dump_lua = true
priority = 100000

# Custom hyperoperation effects

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''elseif eval_type == 'hyper_chips' then
	sound = 'talisman_eeechip''''
position = "at"
payload = '''
elseif eval_type == 'hyper_chips' then
    amt[1] = math.max(amt[1], -3)
	sound = may.get_operation_sound(amt[1], 'chips')
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''elseif eval_type == 'hyper_mult' then
	sound = 'talisman_eeemult''''
position = "at"
payload = '''
elseif eval_type == 'hyper_mult' then
    amt[1] = math.max(amt[1], -3)
	sound = may.get_operation_sound(amt[1], 'mult')
'''
match_indent = true

# man
[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/utils.lua"]'''
pattern = '''return (ret == 1 and 0) or (ret > 0 and ret) or 0'''
position = "at"
payload = '''return (to_big(ret) == to_big(1) and 0) or (to_big(ret) > to_big(0) and ret) or 0'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''if chips > 0 then'''
position = "at"
payload = '''if to_big(chips) ~= to_big(0) then'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''if mult > 0 then'''
position = "at"
payload = '''if to_big(mult) ~= to_big(0) then'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''if x_chips > 0 then'''
position = "at"
payload = '''if to_big(x_chips) > to_big(0) then'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''if e_chips > 0 then'''
position = "at"
payload = '''if to_big(e_chips) > to_big(0) then'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''if ee_chips > 0 then'''
position = "at"
payload = '''if to_big(ee_chips) > to_big(0) then'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''if eee_chips > 0 then'''
position = "at"
payload = '''if to_big(eee_chips) > to_big(0) then'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''if e_mult > 0 then'''
position = "at"
payload = '''if to_big(e_mult) > to_big(0) then'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''if ee_mult> 0 then'''
position = "at"
payload = '''if to_big(ee_mult) > to_big(0) then'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''if eee_mult > 0 then'''
position = "at"
payload = '''if to_big(eee_mult) > to_big(0) then'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''if h_chips ~= 0 then '''
position = "at"
payload = '''if to_big(h_chips) ~= to_big(0) then'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''if h_mult ~= 0 then'''
position = "at"
payload = '''if to_big(h_mult) ~= to_big(0) then'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''if h_x_chips > 0 then'''
position = "at"
payload = '''if to_big(h_x_chips) > to_big(0) then'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''if h_x_mult > 0 then'''
position = "at"
payload = '''if to_big(h_x_mult) > to_big(0) then'''
match_indent = true

# SGWHHSFSHSJSVj GACAXACUABJD DNKDSJ AH SH ENNEOEH AHVAHCWE
[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/utils.lua"]'''
pattern = '''G.GAME.hands[hand].level = G.GAME.hands[hand].level + (type(args.level_up) == 'number' and args.level_up or 1)'''
position = "at"
payload = '''G.GAME.hands[hand].level = G.GAME.hands[hand].level + ((type(args.level_up) == 'number' or type(args.level_up) == 'table') and args.level_up or 1)'''
match_indent = true

# The suffering is endless
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''text = (amt <-0.01 and '-' or '')..localize("$")..tostring(math.abs(amt))
        colour = amt <-0.01 and G.C.RED or G.C.MONEY'''
position = "at"
payload = '''text = (to_big(amt) < to_big(-0.01) and '-' or '')..localize("$")..tostring(math.abs(amt))
        colour = to_big(amt) < to_big(-0.01) and G.C.RED or G.C.MONEY'''
match_indent = true

# ??????????????????
[[patches]]
[patches.pattern]
target = "main.lua"
pattern = '''function math.log(x, y)'''
position = "after"
payload = '''if not x then return (y or 2.718281828459045) end'''
match_indent = true