on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pull from Codeberg
        run: |
          git remote add codeberg https://codeberg.org/BalatroMayhem/Mayhem.git
          git fetch codeberg
          git checkout -b sync-from-codeberg
          git reset --hard codeberg/main

      - name: Create Pull Request # RUN A PR BOI
        uses: repo-sync/pull-request@v2
        with:
          source_branch: 'sync-from-codeberg'
          destination_branch: 'main'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: 'Sync updates from Codeberg'
          pr_body: 'This PR automatically synchronizes the repository with the latest changes from Codeberg.'
