on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout local repository # do the thing no 1
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Mirror Codeberg to GitHub
        uses: cssnr/mirror-repository-action@master
        with:
          url: 'https://codeberg.org/BalatroMayhem/Mayhem.git' # do the thing no 2
          username: ${{ secrets.CODEBERG_USERNAME }}
          password: ${{ secrets.CODEBERG_TOKEN }} # YOU WILL NEVER KNOW
